pipeline {
  agent any
  stages {
    stage('Build') {
      steps {
        //   cmakeBuild(
        //     installation: 'InSearchPath'
        //   )
        sh 'echo "Building..."'
        sh 'chmod +x installer.sh'
        sh './installer.sh'
        archiveArtifacts artifacts: '/out/build/*', fingerprint: true
      }
    }
    stage('Test') {
      steps {
        //   cmakeBuild(
        //     installation: 'InSearchPath'
        //   )
        sh 'echo "Running..."'
        sh 'chmod +x run.sh'
        sh './run.sh'
      }
    }
  }
}